// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test.proto

#include "Test.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_Test_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_TestGrandchildMessage_Test_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_Test_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_TestChildMessage_Test_2eproto;
namespace testPackage {
class TestGrandchildMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TestGrandchildMessage> _instance;
} _TestGrandchildMessage_default_instance_;
class TestChildMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TestChildMessage> _instance;
} _TestChildMessage_default_instance_;
class TestMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TestMessage> _instance;
} _TestMessage_default_instance_;
}  // namespace testPackage
static void InitDefaultsTestGrandchildMessage_Test_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::testPackage::_TestGrandchildMessage_default_instance_;
    new (ptr) ::testPackage::TestGrandchildMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::testPackage::TestGrandchildMessage::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_TestGrandchildMessage_Test_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsTestGrandchildMessage_Test_2eproto}, {}};

static void InitDefaultsTestChildMessage_Test_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::testPackage::_TestChildMessage_default_instance_;
    new (ptr) ::testPackage::TestChildMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::testPackage::TestChildMessage::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_TestChildMessage_Test_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsTestChildMessage_Test_2eproto}, {
      &scc_info_TestGrandchildMessage_Test_2eproto.base,}};

static void InitDefaultsTestMessage_Test_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::testPackage::_TestMessage_default_instance_;
    new (ptr) ::testPackage::TestMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::testPackage::TestMessage::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_TestMessage_Test_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsTestMessage_Test_2eproto}, {
      &scc_info_TestChildMessage_Test_2eproto.base,}};

void InitDefaults_Test_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_TestGrandchildMessage_Test_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_TestChildMessage_Test_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_TestMessage_Test_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_Test_2eproto[3];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors_Test_2eproto[1];
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_Test_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_Test_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::testPackage::TestGrandchildMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::testPackage::TestGrandchildMessage, doublefield_),
  PROTOBUF_FIELD_OFFSET(::testPackage::TestGrandchildMessage, repeatedstringlengthstringfield_),
  PROTOBUF_FIELD_OFFSET(::testPackage::TestGrandchildMessage, repeatedstringfield_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::testPackage::TestChildMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::testPackage::TestChildMessage, int32field_),
  PROTOBUF_FIELD_OFFSET(::testPackage::TestChildMessage, stringfield_),
  PROTOBUF_FIELD_OFFSET(::testPackage::TestChildMessage, testgrandchildmessagefield_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::testPackage::TestMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::testPackage::TestMessage, doublefield_),
  PROTOBUF_FIELD_OFFSET(::testPackage::TestMessage, floatfield_),
  PROTOBUF_FIELD_OFFSET(::testPackage::TestMessage, int32field_),
  PROTOBUF_FIELD_OFFSET(::testPackage::TestMessage, int64field_),
  PROTOBUF_FIELD_OFFSET(::testPackage::TestMessage, uint32field_),
  PROTOBUF_FIELD_OFFSET(::testPackage::TestMessage, uint64field_),
  PROTOBUF_FIELD_OFFSET(::testPackage::TestMessage, boolfield_),
  PROTOBUF_FIELD_OFFSET(::testPackage::TestMessage, stringfield_),
  PROTOBUF_FIELD_OFFSET(::testPackage::TestMessage, testenumfield_),
  PROTOBUF_FIELD_OFFSET(::testPackage::TestMessage, testchildmessagefield_),
  PROTOBUF_FIELD_OFFSET(::testPackage::TestMessage, repeateddoublelengthdoublefield_),
  PROTOBUF_FIELD_OFFSET(::testPackage::TestMessage, repeateddoublefield_),
  PROTOBUF_FIELD_OFFSET(::testPackage::TestMessage, repeatedstringlengthstringfield_),
  PROTOBUF_FIELD_OFFSET(::testPackage::TestMessage, repeatedstringfield_),
  PROTOBUF_FIELD_OFFSET(::testPackage::TestMessage, repeatedtestchildmessagelengthtestchildmessagefield_),
  PROTOBUF_FIELD_OFFSET(::testPackage::TestMessage, repeatedtestchildmessagefield_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::testPackage::TestGrandchildMessage)},
  { 8, -1, sizeof(::testPackage::TestChildMessage)},
  { 16, -1, sizeof(::testPackage::TestMessage)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::testPackage::_TestGrandchildMessage_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::testPackage::_TestChildMessage_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::testPackage::_TestMessage_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_Test_2eproto = {
  {}, AddDescriptors_Test_2eproto, "Test.proto", schemas,
  file_default_instances, TableStruct_Test_2eproto::offsets,
  file_level_metadata_Test_2eproto, 3, file_level_enum_descriptors_Test_2eproto, file_level_service_descriptors_Test_2eproto,
};

const char descriptor_table_protodef_Test_2eproto[] =
  "\n\nTest.proto\022\013testPackage\"r\n\025TestGrandch"
  "ildMessage\022\023\n\013doubleField\030\001 \001(\001\022\'\n\037repea"
  "tedStringLengthStringField\030\002 \001(\004\022\033\n\023repe"
  "atedStringField\030\003 \003(\t\"\203\001\n\020TestChildMessa"
  "ge\022\022\n\nint32Field\030\001 \001(\005\022\023\n\013stringField\030\002 "
  "\001(\t\022F\n\032testGrandchildMessageField\030\003 \001(\0132"
  "\".testPackage.TestGrandchildMessage\"\253\004\n\013"
  "TestMessage\022\023\n\013doubleField\030\001 \001(\001\022\022\n\nfloa"
  "tField\030\002 \001(\002\022\022\n\nint32Field\030\003 \001(\005\022\022\n\nint6"
  "4Field\030\004 \001(\003\022\023\n\013uint32Field\030\005 \001(\r\022\023\n\013uin"
  "t64Field\030\006 \001(\004\022\021\n\tboolField\030\007 \001(\010\022\023\n\013str"
  "ingField\030\010 \001(\t\022,\n\rtestEnumField\030\t \001(\0162\025."
  "testPackage.TestEnum\022<\n\025testChildMessage"
  "Field\030\n \001(\0132\035.testPackage.TestChildMessa"
  "ge\022\'\n\037repeatedDoubleLengthDoubleField\030\013 "
  "\001(\004\022\033\n\023repeatedDoubleField\030\014 \003(\001\022\'\n\037repe"
  "atedStringLengthStringField\030\r \001(\004\022\033\n\023rep"
  "eatedStringField\030\016 \003(\t\022;\n3repeatedTestCh"
  "ildMessageLengthTestChildMessageField\030\017 "
  "\001(\004\022D\n\035repeatedTestChildMessageField\030\020 \003"
  "(\0132\035.testPackage.TestChildMessage*6\n\010Tes"
  "tEnum\022\t\n\005enum0\020\000\022\t\n\005enum1\020\001\022\t\n\005enum2\020\002\022\t"
  "\n\005enum3\020\003b\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_Test_2eproto = {
  false, InitDefaults_Test_2eproto, 
  descriptor_table_protodef_Test_2eproto,
  "Test.proto", &assign_descriptors_table_Test_2eproto, 897,
};

void AddDescriptors_Test_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_Test_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_Test_2eproto = []() { AddDescriptors_Test_2eproto(); return true; }();
namespace testPackage {
const ::google::protobuf::EnumDescriptor* TestEnum_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&assign_descriptors_table_Test_2eproto);
  return file_level_enum_descriptors_Test_2eproto[0];
}
bool TestEnum_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void TestGrandchildMessage::InitAsDefaultInstance() {
}
class TestGrandchildMessage::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TestGrandchildMessage::kDoubleFieldFieldNumber;
const int TestGrandchildMessage::kRepeatedStringLengthStringFieldFieldNumber;
const int TestGrandchildMessage::kRepeatedStringFieldFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TestGrandchildMessage::TestGrandchildMessage()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:testPackage.TestGrandchildMessage)
}
TestGrandchildMessage::TestGrandchildMessage(const TestGrandchildMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      repeatedstringfield_(from.repeatedstringfield_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&doublefield_, &from.doublefield_,
    static_cast<size_t>(reinterpret_cast<char*>(&repeatedstringlengthstringfield_) -
    reinterpret_cast<char*>(&doublefield_)) + sizeof(repeatedstringlengthstringfield_));
  // @@protoc_insertion_point(copy_constructor:testPackage.TestGrandchildMessage)
}

void TestGrandchildMessage::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_TestGrandchildMessage_Test_2eproto.base);
  ::memset(&doublefield_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&repeatedstringlengthstringfield_) -
      reinterpret_cast<char*>(&doublefield_)) + sizeof(repeatedstringlengthstringfield_));
}

TestGrandchildMessage::~TestGrandchildMessage() {
  // @@protoc_insertion_point(destructor:testPackage.TestGrandchildMessage)
  SharedDtor();
}

void TestGrandchildMessage::SharedDtor() {
}

void TestGrandchildMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TestGrandchildMessage& TestGrandchildMessage::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_TestGrandchildMessage_Test_2eproto.base);
  return *internal_default_instance();
}


void TestGrandchildMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:testPackage.TestGrandchildMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  repeatedstringfield_.Clear();
  ::memset(&doublefield_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&repeatedstringlengthstringfield_) -
      reinterpret_cast<char*>(&doublefield_)) + sizeof(repeatedstringlengthstringfield_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* TestGrandchildMessage::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<TestGrandchildMessage*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // double doubleField = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 9) goto handle_unusual;
        msg->set_doublefield(::google::protobuf::io::UnalignedLoad<double>(ptr));
        ptr += sizeof(double);
        break;
      }
      // uint64 repeatedStringLengthStringField = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        msg->set_repeatedstringlengthstringfield(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // repeated string repeatedStringField = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          ctx->extra_parse_data().SetFieldName("testPackage.TestGrandchildMessage.repeatedStringField");
          object = msg->add_repeatedstringfield();
          if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
            parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
            goto string_till_end;
          }
          GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
          ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
          ptr += size;
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 26 && (ptr += 1));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool TestGrandchildMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:testPackage.TestGrandchildMessage)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // double doubleField = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (9 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &doublefield_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 repeatedStringLengthStringField = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &repeatedstringlengthstringfield_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string repeatedStringField = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_repeatedstringfield()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->repeatedstringfield(this->repeatedstringfield_size() - 1).data(),
            static_cast<int>(this->repeatedstringfield(this->repeatedstringfield_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "testPackage.TestGrandchildMessage.repeatedStringField"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:testPackage.TestGrandchildMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:testPackage.TestGrandchildMessage)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void TestGrandchildMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:testPackage.TestGrandchildMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double doubleField = 1;
  if (this->doublefield() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->doublefield(), output);
  }

  // uint64 repeatedStringLengthStringField = 2;
  if (this->repeatedstringlengthstringfield() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->repeatedstringlengthstringfield(), output);
  }

  // repeated string repeatedStringField = 3;
  for (int i = 0, n = this->repeatedstringfield_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->repeatedstringfield(i).data(), static_cast<int>(this->repeatedstringfield(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "testPackage.TestGrandchildMessage.repeatedStringField");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->repeatedstringfield(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:testPackage.TestGrandchildMessage)
}

::google::protobuf::uint8* TestGrandchildMessage::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:testPackage.TestGrandchildMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double doubleField = 1;
  if (this->doublefield() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->doublefield(), target);
  }

  // uint64 repeatedStringLengthStringField = 2;
  if (this->repeatedstringlengthstringfield() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->repeatedstringlengthstringfield(), target);
  }

  // repeated string repeatedStringField = 3;
  for (int i = 0, n = this->repeatedstringfield_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->repeatedstringfield(i).data(), static_cast<int>(this->repeatedstringfield(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "testPackage.TestGrandchildMessage.repeatedStringField");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(3, this->repeatedstringfield(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:testPackage.TestGrandchildMessage)
  return target;
}

size_t TestGrandchildMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:testPackage.TestGrandchildMessage)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string repeatedStringField = 3;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->repeatedstringfield_size());
  for (int i = 0, n = this->repeatedstringfield_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->repeatedstringfield(i));
  }

  // double doubleField = 1;
  if (this->doublefield() != 0) {
    total_size += 1 + 8;
  }

  // uint64 repeatedStringLengthStringField = 2;
  if (this->repeatedstringlengthstringfield() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->repeatedstringlengthstringfield());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TestGrandchildMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:testPackage.TestGrandchildMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const TestGrandchildMessage* source =
      ::google::protobuf::DynamicCastToGenerated<TestGrandchildMessage>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:testPackage.TestGrandchildMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:testPackage.TestGrandchildMessage)
    MergeFrom(*source);
  }
}

void TestGrandchildMessage::MergeFrom(const TestGrandchildMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:testPackage.TestGrandchildMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  repeatedstringfield_.MergeFrom(from.repeatedstringfield_);
  if (from.doublefield() != 0) {
    set_doublefield(from.doublefield());
  }
  if (from.repeatedstringlengthstringfield() != 0) {
    set_repeatedstringlengthstringfield(from.repeatedstringlengthstringfield());
  }
}

void TestGrandchildMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:testPackage.TestGrandchildMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TestGrandchildMessage::CopyFrom(const TestGrandchildMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:testPackage.TestGrandchildMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestGrandchildMessage::IsInitialized() const {
  return true;
}

void TestGrandchildMessage::Swap(TestGrandchildMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TestGrandchildMessage::InternalSwap(TestGrandchildMessage* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  repeatedstringfield_.InternalSwap(CastToBase(&other->repeatedstringfield_));
  swap(doublefield_, other->doublefield_);
  swap(repeatedstringlengthstringfield_, other->repeatedstringlengthstringfield_);
}

::google::protobuf::Metadata TestGrandchildMessage::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_Test_2eproto);
  return ::file_level_metadata_Test_2eproto[kIndexInFileMessages];
}


// ===================================================================

void TestChildMessage::InitAsDefaultInstance() {
  ::testPackage::_TestChildMessage_default_instance_._instance.get_mutable()->testgrandchildmessagefield_ = const_cast< ::testPackage::TestGrandchildMessage*>(
      ::testPackage::TestGrandchildMessage::internal_default_instance());
}
class TestChildMessage::HasBitSetters {
 public:
  static const ::testPackage::TestGrandchildMessage& testgrandchildmessagefield(const TestChildMessage* msg);
};

const ::testPackage::TestGrandchildMessage&
TestChildMessage::HasBitSetters::testgrandchildmessagefield(const TestChildMessage* msg) {
  return *msg->testgrandchildmessagefield_;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TestChildMessage::kInt32FieldFieldNumber;
const int TestChildMessage::kStringFieldFieldNumber;
const int TestChildMessage::kTestGrandchildMessageFieldFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TestChildMessage::TestChildMessage()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:testPackage.TestChildMessage)
}
TestChildMessage::TestChildMessage(const TestChildMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  stringfield_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.stringfield().size() > 0) {
    stringfield_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.stringfield_);
  }
  if (from.has_testgrandchildmessagefield()) {
    testgrandchildmessagefield_ = new ::testPackage::TestGrandchildMessage(*from.testgrandchildmessagefield_);
  } else {
    testgrandchildmessagefield_ = nullptr;
  }
  int32field_ = from.int32field_;
  // @@protoc_insertion_point(copy_constructor:testPackage.TestChildMessage)
}

void TestChildMessage::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_TestChildMessage_Test_2eproto.base);
  stringfield_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&testgrandchildmessagefield_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&int32field_) -
      reinterpret_cast<char*>(&testgrandchildmessagefield_)) + sizeof(int32field_));
}

TestChildMessage::~TestChildMessage() {
  // @@protoc_insertion_point(destructor:testPackage.TestChildMessage)
  SharedDtor();
}

void TestChildMessage::SharedDtor() {
  stringfield_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete testgrandchildmessagefield_;
}

void TestChildMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TestChildMessage& TestChildMessage::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_TestChildMessage_Test_2eproto.base);
  return *internal_default_instance();
}


void TestChildMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:testPackage.TestChildMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  stringfield_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == nullptr && testgrandchildmessagefield_ != nullptr) {
    delete testgrandchildmessagefield_;
  }
  testgrandchildmessagefield_ = nullptr;
  int32field_ = 0;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* TestChildMessage::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<TestChildMessage*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // int32 int32Field = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_int32field(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // string stringField = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("testPackage.TestChildMessage.stringField");
        object = msg->mutable_stringfield();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // .testPackage.TestGrandchildMessage testGrandchildMessageField = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::testPackage::TestGrandchildMessage::_InternalParse;
        object = msg->mutable_testgrandchildmessagefield();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool TestChildMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:testPackage.TestChildMessage)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 int32Field = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &int32field_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string stringField = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_stringfield()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->stringfield().data(), static_cast<int>(this->stringfield().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "testPackage.TestChildMessage.stringField"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .testPackage.TestGrandchildMessage testGrandchildMessageField = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_testgrandchildmessagefield()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:testPackage.TestChildMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:testPackage.TestChildMessage)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void TestChildMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:testPackage.TestChildMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 int32Field = 1;
  if (this->int32field() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->int32field(), output);
  }

  // string stringField = 2;
  if (this->stringfield().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->stringfield().data(), static_cast<int>(this->stringfield().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "testPackage.TestChildMessage.stringField");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->stringfield(), output);
  }

  // .testPackage.TestGrandchildMessage testGrandchildMessageField = 3;
  if (this->has_testgrandchildmessagefield()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, HasBitSetters::testgrandchildmessagefield(this), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:testPackage.TestChildMessage)
}

::google::protobuf::uint8* TestChildMessage::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:testPackage.TestChildMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 int32Field = 1;
  if (this->int32field() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->int32field(), target);
  }

  // string stringField = 2;
  if (this->stringfield().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->stringfield().data(), static_cast<int>(this->stringfield().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "testPackage.TestChildMessage.stringField");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->stringfield(), target);
  }

  // .testPackage.TestGrandchildMessage testGrandchildMessageField = 3;
  if (this->has_testgrandchildmessagefield()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, HasBitSetters::testgrandchildmessagefield(this), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:testPackage.TestChildMessage)
  return target;
}

size_t TestChildMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:testPackage.TestChildMessage)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string stringField = 2;
  if (this->stringfield().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->stringfield());
  }

  // .testPackage.TestGrandchildMessage testGrandchildMessageField = 3;
  if (this->has_testgrandchildmessagefield()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *testgrandchildmessagefield_);
  }

  // int32 int32Field = 1;
  if (this->int32field() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->int32field());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TestChildMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:testPackage.TestChildMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const TestChildMessage* source =
      ::google::protobuf::DynamicCastToGenerated<TestChildMessage>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:testPackage.TestChildMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:testPackage.TestChildMessage)
    MergeFrom(*source);
  }
}

void TestChildMessage::MergeFrom(const TestChildMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:testPackage.TestChildMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.stringfield().size() > 0) {

    stringfield_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.stringfield_);
  }
  if (from.has_testgrandchildmessagefield()) {
    mutable_testgrandchildmessagefield()->::testPackage::TestGrandchildMessage::MergeFrom(from.testgrandchildmessagefield());
  }
  if (from.int32field() != 0) {
    set_int32field(from.int32field());
  }
}

void TestChildMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:testPackage.TestChildMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TestChildMessage::CopyFrom(const TestChildMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:testPackage.TestChildMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestChildMessage::IsInitialized() const {
  return true;
}

void TestChildMessage::Swap(TestChildMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TestChildMessage::InternalSwap(TestChildMessage* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  stringfield_.Swap(&other->stringfield_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(testgrandchildmessagefield_, other->testgrandchildmessagefield_);
  swap(int32field_, other->int32field_);
}

::google::protobuf::Metadata TestChildMessage::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_Test_2eproto);
  return ::file_level_metadata_Test_2eproto[kIndexInFileMessages];
}


// ===================================================================

void TestMessage::InitAsDefaultInstance() {
  ::testPackage::_TestMessage_default_instance_._instance.get_mutable()->testchildmessagefield_ = const_cast< ::testPackage::TestChildMessage*>(
      ::testPackage::TestChildMessage::internal_default_instance());
}
class TestMessage::HasBitSetters {
 public:
  static const ::testPackage::TestChildMessage& testchildmessagefield(const TestMessage* msg);
};

const ::testPackage::TestChildMessage&
TestMessage::HasBitSetters::testchildmessagefield(const TestMessage* msg) {
  return *msg->testchildmessagefield_;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TestMessage::kDoubleFieldFieldNumber;
const int TestMessage::kFloatFieldFieldNumber;
const int TestMessage::kInt32FieldFieldNumber;
const int TestMessage::kInt64FieldFieldNumber;
const int TestMessage::kUint32FieldFieldNumber;
const int TestMessage::kUint64FieldFieldNumber;
const int TestMessage::kBoolFieldFieldNumber;
const int TestMessage::kStringFieldFieldNumber;
const int TestMessage::kTestEnumFieldFieldNumber;
const int TestMessage::kTestChildMessageFieldFieldNumber;
const int TestMessage::kRepeatedDoubleLengthDoubleFieldFieldNumber;
const int TestMessage::kRepeatedDoubleFieldFieldNumber;
const int TestMessage::kRepeatedStringLengthStringFieldFieldNumber;
const int TestMessage::kRepeatedStringFieldFieldNumber;
const int TestMessage::kRepeatedTestChildMessageLengthTestChildMessageFieldFieldNumber;
const int TestMessage::kRepeatedTestChildMessageFieldFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TestMessage::TestMessage()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:testPackage.TestMessage)
}
TestMessage::TestMessage(const TestMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      repeateddoublefield_(from.repeateddoublefield_),
      repeatedstringfield_(from.repeatedstringfield_),
      repeatedtestchildmessagefield_(from.repeatedtestchildmessagefield_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  stringfield_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.stringfield().size() > 0) {
    stringfield_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.stringfield_);
  }
  if (from.has_testchildmessagefield()) {
    testchildmessagefield_ = new ::testPackage::TestChildMessage(*from.testchildmessagefield_);
  } else {
    testchildmessagefield_ = nullptr;
  }
  ::memcpy(&doublefield_, &from.doublefield_,
    static_cast<size_t>(reinterpret_cast<char*>(&testenumfield_) -
    reinterpret_cast<char*>(&doublefield_)) + sizeof(testenumfield_));
  // @@protoc_insertion_point(copy_constructor:testPackage.TestMessage)
}

void TestMessage::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_TestMessage_Test_2eproto.base);
  stringfield_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&testchildmessagefield_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&testenumfield_) -
      reinterpret_cast<char*>(&testchildmessagefield_)) + sizeof(testenumfield_));
}

TestMessage::~TestMessage() {
  // @@protoc_insertion_point(destructor:testPackage.TestMessage)
  SharedDtor();
}

void TestMessage::SharedDtor() {
  stringfield_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete testchildmessagefield_;
}

void TestMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TestMessage& TestMessage::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_TestMessage_Test_2eproto.base);
  return *internal_default_instance();
}


void TestMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:testPackage.TestMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  repeateddoublefield_.Clear();
  repeatedstringfield_.Clear();
  repeatedtestchildmessagefield_.Clear();
  stringfield_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == nullptr && testchildmessagefield_ != nullptr) {
    delete testchildmessagefield_;
  }
  testchildmessagefield_ = nullptr;
  ::memset(&doublefield_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&testenumfield_) -
      reinterpret_cast<char*>(&doublefield_)) + sizeof(testenumfield_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* TestMessage::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<TestMessage*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // double doubleField = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 9) goto handle_unusual;
        msg->set_doublefield(::google::protobuf::io::UnalignedLoad<double>(ptr));
        ptr += sizeof(double);
        break;
      }
      // float floatField = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 21) goto handle_unusual;
        msg->set_floatfield(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // int32 int32Field = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 24) goto handle_unusual;
        msg->set_int32field(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // int64 int64Field = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 32) goto handle_unusual;
        msg->set_int64field(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // uint32 uint32Field = 5;
      case 5: {
        if (static_cast<::google::protobuf::uint8>(tag) != 40) goto handle_unusual;
        msg->set_uint32field(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // uint64 uint64Field = 6;
      case 6: {
        if (static_cast<::google::protobuf::uint8>(tag) != 48) goto handle_unusual;
        msg->set_uint64field(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // bool boolField = 7;
      case 7: {
        if (static_cast<::google::protobuf::uint8>(tag) != 56) goto handle_unusual;
        msg->set_boolfield(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // string stringField = 8;
      case 8: {
        if (static_cast<::google::protobuf::uint8>(tag) != 66) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("testPackage.TestMessage.stringField");
        object = msg->mutable_stringfield();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // .testPackage.TestEnum testEnumField = 9;
      case 9: {
        if (static_cast<::google::protobuf::uint8>(tag) != 72) goto handle_unusual;
        ::google::protobuf::uint64 val = ::google::protobuf::internal::ReadVarint(&ptr);
        msg->set_testenumfield(static_cast<::testPackage::TestEnum>(val));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // .testPackage.TestChildMessage testChildMessageField = 10;
      case 10: {
        if (static_cast<::google::protobuf::uint8>(tag) != 82) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::testPackage::TestChildMessage::_InternalParse;
        object = msg->mutable_testchildmessagefield();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      // uint64 repeatedDoubleLengthDoubleField = 11;
      case 11: {
        if (static_cast<::google::protobuf::uint8>(tag) != 88) goto handle_unusual;
        msg->set_repeateddoublelengthdoublefield(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // repeated double repeatedDoubleField = 12;
      case 12: {
        if (static_cast<::google::protobuf::uint8>(tag) == 98) {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::google::protobuf::internal::PackedDoubleParser;
          object = msg->mutable_repeateddoublefield();
          if (size > end - ptr) goto len_delim_till_end;
          auto newend = ptr + size;
          if (size) ptr = parser_till_end(ptr, newend, object, ctx);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr == newend);
          break;
        } else if (static_cast<::google::protobuf::uint8>(tag) != 97) goto handle_unusual;
        do {
          msg->add_repeateddoublefield(::google::protobuf::io::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 97 && (ptr += 1));
        break;
      }
      // uint64 repeatedStringLengthStringField = 13;
      case 13: {
        if (static_cast<::google::protobuf::uint8>(tag) != 104) goto handle_unusual;
        msg->set_repeatedstringlengthstringfield(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // repeated string repeatedStringField = 14;
      case 14: {
        if (static_cast<::google::protobuf::uint8>(tag) != 114) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          ctx->extra_parse_data().SetFieldName("testPackage.TestMessage.repeatedStringField");
          object = msg->add_repeatedstringfield();
          if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
            parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
            goto string_till_end;
          }
          GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
          ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
          ptr += size;
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 114 && (ptr += 1));
        break;
      }
      // uint64 repeatedTestChildMessageLengthTestChildMessageField = 15;
      case 15: {
        if (static_cast<::google::protobuf::uint8>(tag) != 120) goto handle_unusual;
        msg->set_repeatedtestchildmessagelengthtestchildmessagefield(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // repeated .testPackage.TestChildMessage repeatedTestChildMessageField = 16;
      case 16: {
        if (static_cast<::google::protobuf::uint8>(tag) != 130) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::testPackage::TestChildMessage::_InternalParse;
          object = msg->add_repeatedtestchildmessagefield();
          if (size > end - ptr) goto len_delim_till_end;
          ptr += size;
          GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
              {parser_till_end, object}, ptr - size, ptr));
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 65535) == 386 && (ptr += 2));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool TestMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:testPackage.TestMessage)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(16383u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // double doubleField = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (9 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &doublefield_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float floatField = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (21 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &floatfield_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 int32Field = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (24 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &int32field_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 int64Field = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (32 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &int64field_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 uint32Field = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (40 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &uint32field_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 uint64Field = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (48 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &uint64field_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool boolField = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (56 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &boolfield_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string stringField = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (66 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_stringfield()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->stringfield().data(), static_cast<int>(this->stringfield().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "testPackage.TestMessage.stringField"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .testPackage.TestEnum testEnumField = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (72 & 0xFF)) {
          int value = 0;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_testenumfield(static_cast< ::testPackage::TestEnum >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .testPackage.TestChildMessage testChildMessageField = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (82 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_testchildmessagefield()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 repeatedDoubleLengthDoubleField = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (88 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &repeateddoublelengthdoublefield_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated double repeatedDoubleField = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (98 & 0xFF)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_repeateddoublefield())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) == (97 & 0xFF)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 98u, input, this->mutable_repeateddoublefield())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 repeatedStringLengthStringField = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (104 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &repeatedstringlengthstringfield_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string repeatedStringField = 14;
      case 14: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (114 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_repeatedstringfield()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->repeatedstringfield(this->repeatedstringfield_size() - 1).data(),
            static_cast<int>(this->repeatedstringfield(this->repeatedstringfield_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "testPackage.TestMessage.repeatedStringField"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 repeatedTestChildMessageLengthTestChildMessageField = 15;
      case 15: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (120 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &repeatedtestchildmessagelengthtestchildmessagefield_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .testPackage.TestChildMessage repeatedTestChildMessageField = 16;
      case 16: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (130 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_repeatedtestchildmessagefield()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:testPackage.TestMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:testPackage.TestMessage)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void TestMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:testPackage.TestMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double doubleField = 1;
  if (this->doublefield() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->doublefield(), output);
  }

  // float floatField = 2;
  if (this->floatfield() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->floatfield(), output);
  }

  // int32 int32Field = 3;
  if (this->int32field() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->int32field(), output);
  }

  // int64 int64Field = 4;
  if (this->int64field() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->int64field(), output);
  }

  // uint32 uint32Field = 5;
  if (this->uint32field() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->uint32field(), output);
  }

  // uint64 uint64Field = 6;
  if (this->uint64field() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(6, this->uint64field(), output);
  }

  // bool boolField = 7;
  if (this->boolfield() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(7, this->boolfield(), output);
  }

  // string stringField = 8;
  if (this->stringfield().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->stringfield().data(), static_cast<int>(this->stringfield().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "testPackage.TestMessage.stringField");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->stringfield(), output);
  }

  // .testPackage.TestEnum testEnumField = 9;
  if (this->testenumfield() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      9, this->testenumfield(), output);
  }

  // .testPackage.TestChildMessage testChildMessageField = 10;
  if (this->has_testchildmessagefield()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      10, HasBitSetters::testchildmessagefield(this), output);
  }

  // uint64 repeatedDoubleLengthDoubleField = 11;
  if (this->repeateddoublelengthdoublefield() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(11, this->repeateddoublelengthdoublefield(), output);
  }

  // repeated double repeatedDoubleField = 12;
  if (this->repeateddoublefield_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(12, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_repeateddoublefield_cached_byte_size_.load(
        std::memory_order_relaxed));
    ::google::protobuf::internal::WireFormatLite::WriteDoubleArray(
      this->repeateddoublefield().data(), this->repeateddoublefield_size(), output);
  }

  // uint64 repeatedStringLengthStringField = 13;
  if (this->repeatedstringlengthstringfield() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(13, this->repeatedstringlengthstringfield(), output);
  }

  // repeated string repeatedStringField = 14;
  for (int i = 0, n = this->repeatedstringfield_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->repeatedstringfield(i).data(), static_cast<int>(this->repeatedstringfield(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "testPackage.TestMessage.repeatedStringField");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      14, this->repeatedstringfield(i), output);
  }

  // uint64 repeatedTestChildMessageLengthTestChildMessageField = 15;
  if (this->repeatedtestchildmessagelengthtestchildmessagefield() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(15, this->repeatedtestchildmessagelengthtestchildmessagefield(), output);
  }

  // repeated .testPackage.TestChildMessage repeatedTestChildMessageField = 16;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->repeatedtestchildmessagefield_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      16,
      this->repeatedtestchildmessagefield(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:testPackage.TestMessage)
}

::google::protobuf::uint8* TestMessage::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:testPackage.TestMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double doubleField = 1;
  if (this->doublefield() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->doublefield(), target);
  }

  // float floatField = 2;
  if (this->floatfield() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->floatfield(), target);
  }

  // int32 int32Field = 3;
  if (this->int32field() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->int32field(), target);
  }

  // int64 int64Field = 4;
  if (this->int64field() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(4, this->int64field(), target);
  }

  // uint32 uint32Field = 5;
  if (this->uint32field() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->uint32field(), target);
  }

  // uint64 uint64Field = 6;
  if (this->uint64field() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(6, this->uint64field(), target);
  }

  // bool boolField = 7;
  if (this->boolfield() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(7, this->boolfield(), target);
  }

  // string stringField = 8;
  if (this->stringfield().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->stringfield().data(), static_cast<int>(this->stringfield().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "testPackage.TestMessage.stringField");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->stringfield(), target);
  }

  // .testPackage.TestEnum testEnumField = 9;
  if (this->testenumfield() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      9, this->testenumfield(), target);
  }

  // .testPackage.TestChildMessage testChildMessageField = 10;
  if (this->has_testchildmessagefield()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        10, HasBitSetters::testchildmessagefield(this), target);
  }

  // uint64 repeatedDoubleLengthDoubleField = 11;
  if (this->repeateddoublelengthdoublefield() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(11, this->repeateddoublelengthdoublefield(), target);
  }

  // repeated double repeatedDoubleField = 12;
  if (this->repeateddoublefield_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      12,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        _repeateddoublefield_cached_byte_size_.load(std::memory_order_relaxed),
         target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleNoTagToArray(this->repeateddoublefield_, target);
  }

  // uint64 repeatedStringLengthStringField = 13;
  if (this->repeatedstringlengthstringfield() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(13, this->repeatedstringlengthstringfield(), target);
  }

  // repeated string repeatedStringField = 14;
  for (int i = 0, n = this->repeatedstringfield_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->repeatedstringfield(i).data(), static_cast<int>(this->repeatedstringfield(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "testPackage.TestMessage.repeatedStringField");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(14, this->repeatedstringfield(i), target);
  }

  // uint64 repeatedTestChildMessageLengthTestChildMessageField = 15;
  if (this->repeatedtestchildmessagelengthtestchildmessagefield() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(15, this->repeatedtestchildmessagelengthtestchildmessagefield(), target);
  }

  // repeated .testPackage.TestChildMessage repeatedTestChildMessageField = 16;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->repeatedtestchildmessagefield_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        16, this->repeatedtestchildmessagefield(static_cast<int>(i)), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:testPackage.TestMessage)
  return target;
}

size_t TestMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:testPackage.TestMessage)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated double repeatedDoubleField = 12;
  {
    unsigned int count = static_cast<unsigned int>(this->repeateddoublefield_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast<::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    _repeateddoublefield_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated string repeatedStringField = 14;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->repeatedstringfield_size());
  for (int i = 0, n = this->repeatedstringfield_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->repeatedstringfield(i));
  }

  // repeated .testPackage.TestChildMessage repeatedTestChildMessageField = 16;
  {
    unsigned int count = static_cast<unsigned int>(this->repeatedtestchildmessagefield_size());
    total_size += 2UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->repeatedtestchildmessagefield(static_cast<int>(i)));
    }
  }

  // string stringField = 8;
  if (this->stringfield().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->stringfield());
  }

  // .testPackage.TestChildMessage testChildMessageField = 10;
  if (this->has_testchildmessagefield()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *testchildmessagefield_);
  }

  // double doubleField = 1;
  if (this->doublefield() != 0) {
    total_size += 1 + 8;
  }

  // float floatField = 2;
  if (this->floatfield() != 0) {
    total_size += 1 + 4;
  }

  // int32 int32Field = 3;
  if (this->int32field() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->int32field());
  }

  // int64 int64Field = 4;
  if (this->int64field() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->int64field());
  }

  // uint64 uint64Field = 6;
  if (this->uint64field() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->uint64field());
  }

  // uint32 uint32Field = 5;
  if (this->uint32field() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->uint32field());
  }

  // bool boolField = 7;
  if (this->boolfield() != 0) {
    total_size += 1 + 1;
  }

  // uint64 repeatedDoubleLengthDoubleField = 11;
  if (this->repeateddoublelengthdoublefield() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->repeateddoublelengthdoublefield());
  }

  // uint64 repeatedStringLengthStringField = 13;
  if (this->repeatedstringlengthstringfield() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->repeatedstringlengthstringfield());
  }

  // uint64 repeatedTestChildMessageLengthTestChildMessageField = 15;
  if (this->repeatedtestchildmessagelengthtestchildmessagefield() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->repeatedtestchildmessagelengthtestchildmessagefield());
  }

  // .testPackage.TestEnum testEnumField = 9;
  if (this->testenumfield() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->testenumfield());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TestMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:testPackage.TestMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const TestMessage* source =
      ::google::protobuf::DynamicCastToGenerated<TestMessage>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:testPackage.TestMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:testPackage.TestMessage)
    MergeFrom(*source);
  }
}

void TestMessage::MergeFrom(const TestMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:testPackage.TestMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  repeateddoublefield_.MergeFrom(from.repeateddoublefield_);
  repeatedstringfield_.MergeFrom(from.repeatedstringfield_);
  repeatedtestchildmessagefield_.MergeFrom(from.repeatedtestchildmessagefield_);
  if (from.stringfield().size() > 0) {

    stringfield_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.stringfield_);
  }
  if (from.has_testchildmessagefield()) {
    mutable_testchildmessagefield()->::testPackage::TestChildMessage::MergeFrom(from.testchildmessagefield());
  }
  if (from.doublefield() != 0) {
    set_doublefield(from.doublefield());
  }
  if (from.floatfield() != 0) {
    set_floatfield(from.floatfield());
  }
  if (from.int32field() != 0) {
    set_int32field(from.int32field());
  }
  if (from.int64field() != 0) {
    set_int64field(from.int64field());
  }
  if (from.uint64field() != 0) {
    set_uint64field(from.uint64field());
  }
  if (from.uint32field() != 0) {
    set_uint32field(from.uint32field());
  }
  if (from.boolfield() != 0) {
    set_boolfield(from.boolfield());
  }
  if (from.repeateddoublelengthdoublefield() != 0) {
    set_repeateddoublelengthdoublefield(from.repeateddoublelengthdoublefield());
  }
  if (from.repeatedstringlengthstringfield() != 0) {
    set_repeatedstringlengthstringfield(from.repeatedstringlengthstringfield());
  }
  if (from.repeatedtestchildmessagelengthtestchildmessagefield() != 0) {
    set_repeatedtestchildmessagelengthtestchildmessagefield(from.repeatedtestchildmessagelengthtestchildmessagefield());
  }
  if (from.testenumfield() != 0) {
    set_testenumfield(from.testenumfield());
  }
}

void TestMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:testPackage.TestMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TestMessage::CopyFrom(const TestMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:testPackage.TestMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestMessage::IsInitialized() const {
  return true;
}

void TestMessage::Swap(TestMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TestMessage::InternalSwap(TestMessage* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  repeateddoublefield_.InternalSwap(&other->repeateddoublefield_);
  repeatedstringfield_.InternalSwap(CastToBase(&other->repeatedstringfield_));
  CastToBase(&repeatedtestchildmessagefield_)->InternalSwap(CastToBase(&other->repeatedtestchildmessagefield_));
  stringfield_.Swap(&other->stringfield_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(testchildmessagefield_, other->testchildmessagefield_);
  swap(doublefield_, other->doublefield_);
  swap(floatfield_, other->floatfield_);
  swap(int32field_, other->int32field_);
  swap(int64field_, other->int64field_);
  swap(uint64field_, other->uint64field_);
  swap(uint32field_, other->uint32field_);
  swap(boolfield_, other->boolfield_);
  swap(repeateddoublelengthdoublefield_, other->repeateddoublelengthdoublefield_);
  swap(repeatedstringlengthstringfield_, other->repeatedstringlengthstringfield_);
  swap(repeatedtestchildmessagelengthtestchildmessagefield_, other->repeatedtestchildmessagelengthtestchildmessagefield_);
  swap(testenumfield_, other->testenumfield_);
}

::google::protobuf::Metadata TestMessage::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_Test_2eproto);
  return ::file_level_metadata_Test_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace testPackage
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::testPackage::TestGrandchildMessage* Arena::CreateMaybeMessage< ::testPackage::TestGrandchildMessage >(Arena* arena) {
  return Arena::CreateInternal< ::testPackage::TestGrandchildMessage >(arena);
}
template<> PROTOBUF_NOINLINE ::testPackage::TestChildMessage* Arena::CreateMaybeMessage< ::testPackage::TestChildMessage >(Arena* arena) {
  return Arena::CreateInternal< ::testPackage::TestChildMessage >(arena);
}
template<> PROTOBUF_NOINLINE ::testPackage::TestMessage* Arena::CreateMaybeMessage< ::testPackage::TestMessage >(Arena* arena) {
  return Arena::CreateInternal< ::testPackage::TestMessage >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
